# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20160419_0616'),
        ('objects', '0005_auto_20150403_2339'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_poses_here', to='objects.ObjectDB')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_poses', to='objects.ObjectDB')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='bbs.Post'),
        ),
    ]
