# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('public_update', models.DateTimeField(null=True)),
                ('admin_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('lock_storage', models.TextField(blank=True, verbose_name='locks')),
                ('anonymous', models.BooleanField(default=False)),
                ('due', models.DurationField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('date_made', models.DateTimeField()),
                ('comment_mode', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handler', models.BooleanField(default=False)),
                ('is_helper', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField(null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_handling', to='objects.ObjectDB')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='jobs.Job')),
            ],
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.JobHandler'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.JobCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='jobhandler',
            unique_together=set([('character', 'job')]),
        ),
    ]
