# Generated by Django 2.2.6 on 2019-11-25 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumboarddb',
            name='db_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='forum.ForumCategoryDB'),
        ),
        migrations.AlterField(
            model_name='forumboarddb',
            name='db_ignore_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
