# Generated by Django 2.2.6 on 2019-11-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191125_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumboarddb',
            old_name='db_ignore_list',
            new_name='ignore_list',
        ),
    ]
