# Generated by Django 2.2.6 on 2019-11-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191125_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpostdb',
            name='db_date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forumpostdb',
            name='db_date_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forumthreaddb',
            name='db_date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forumthreaddb',
            name='db_date_modified',
            field=models.DateTimeField(),
        ),
    ]
