# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 21:18
from __future__ import unicode_literals

import athanor.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('comms', '0009_auto_20160921_1731'),
        ('bbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.BooleanField(default=True)),
                ('color', models.CharField(default='n', max_length=20, validators=[athanor.core.models.validate_color])),
                ('color_titles', models.BooleanField(default=True)),
                ('title_length', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_nospoof', models.BooleanField(default=False)),
                ('group_ic', models.BooleanField(default=True)),
                ('group_ooc', models.BooleanField(default=True)),
                ('last_played', models.DateTimeField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('slot_cost', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveSmallIntegerField(db_index=True, default=1, unique=True)),
                ('bbs_enabled', models.BooleanField(default=True)),
                ('gbs_enabled', models.BooleanField(default=True)),
                ('guest_post', models.BooleanField(default=True)),
                ('staff_tag', models.CharField(default='r', max_length=25)),
                ('fclist_enabled', models.BooleanField(default=True)),
                ('max_themes', models.PositiveSmallIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('guest_rename', models.BooleanField(default=True)),
                ('pot_enabled', models.BooleanField(default=True)),
                ('pot_timeout', models.PositiveIntegerField(default=28800)),
                ('pot_number', models.PositiveIntegerField(default=300)),
                ('events_enabled', models.BooleanField(default=True)),
                ('groups_enabled', models.BooleanField(default=True)),
                ('group_ic', models.BooleanField(default=True)),
                ('group_ooc', models.BooleanField(default=True)),
                ('anon_notices', models.BooleanField(default=False)),
                ('public_email', models.EmailField(max_length=254, null=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('job_enabled', models.BooleanField(default=True)),
                ('open_players', models.BooleanField(default=True)),
                ('open_characters', models.BooleanField(default=True)),
                ('admin_channels', models.ManyToManyField(related_name='_gamesetting_admin_channels_+', to='comms.ChannelDB')),
                ('alerts_channels', models.ManyToManyField(related_name='_gamesetting_alerts_channels_+', to='comms.ChannelDB')),
                ('approve_channels', models.ManyToManyField(related_name='_gamesetting_approve_channels_+', to='comms.ChannelDB')),
                ('character_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.ObjectDB')),
                ('default_channels', models.ManyToManyField(related_name='_gamesetting_default_channels_+', to='comms.ChannelDB')),
                ('event_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bbs.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('site', models.CharField(max_length=300)),
                ('result', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emit', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('codename', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms.ChannelDB')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Muzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DurationField()),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to='comms.ChannelDB')),
                ('setby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_alert', models.BooleanField(default=True)),
                ('bbscan_alert', models.BooleanField(default=True)),
                ('mail_alert', models.BooleanField(default=True)),
                ('events_alert', models.BooleanField(default=True)),
                ('namelink_channel', models.BooleanField(default=True)),
                ('quotes_channel', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('speech_channel', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('border_color', models.CharField(default='M', max_length=25, validators=[athanor.core.models.validate_color])),
                ('column_color', models.CharField(default='G', max_length=25, validators=[athanor.core.models.validate_color])),
                ('headerstar_color', models.CharField(default='m', max_length=25, validators=[athanor.core.models.validate_color])),
                ('headertext_color', models.CharField(default='w', max_length=25, validators=[athanor.core.models.validate_color])),
                ('msgborder_color', models.CharField(default='m', max_length=25, validators=[athanor.core.models.validate_color])),
                ('msgtext_color', models.CharField(default='w', max_length=25, validators=[athanor.core.models.validate_color])),
                ('oocborder_color', models.CharField(default='x', max_length=25, validators=[athanor.core.models.validate_color])),
                ('ooctext_color', models.CharField(default='r', max_length=25, validators=[athanor.core.models.validate_color])),
                ('page_color', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('outpage_color', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('exitname_color', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('exitalias_color', models.CharField(default='n', max_length=25, validators=[athanor.core.models.validate_color])),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('penn_channels', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_slots', models.SmallIntegerField(default=0)),
                ('last_played', models.DateTimeField(null=True)),
                ('channel_muzzles', models.ManyToManyField(related_name='player_muzzles', to='core.Muzzle')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_settings', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(related_name='on_watch', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='PuppetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppet_logs', to='objects.ObjectDB')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppet_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('duty', models.BooleanField(default=False)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_entry', to='objects.ObjectDB')),
            ],
        ),
    ]
