# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0002_auto_20160818_2137'),
        ('comms', '0007_msg_db_tags'),
        ('objects', '0005_auto_20150403_2339'),
        ('jobs', '0001_initial'),
        ('groups', '0001_initial'),
        ('fclist', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='job_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.JobCategory'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='roleplay_channels',
            field=models.ManyToManyField(related_name='_gamesetting_roleplay_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='scene_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bbs.Board'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='channel_gags',
            field=models.ManyToManyField(related_name='character_gags', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='channel_muzzles',
            field=models.ManyToManyField(related_name='character_muzzles', to='core.Muzzle'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_settings', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='fclist.CharacterStatus'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='fclist.CharacterType'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='group_focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelsetting',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='channelsetting',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='groups.Group'),
        ),
    ]
