# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160818_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersetting',
            name='channel_muzzles',
            field=models.ManyToManyField(related_name='player_muzzles', to='core.Muzzle'),
        ),
        migrations.AddField(
            model_name='playersetting',
            name='last_played',
            field=models.DateTimeField(null=True),
        ),
    ]
