# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160818_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppetlog',
            name='unpuppet',
        ),
    ]
