# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('submit_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lock_storage', models.TextField(blank=True, verbose_name='locks')),
            ],
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('date_made', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handler', models.BooleanField(default=False)),
                ('is_helper', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_handling', to='objects.ObjectDB')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='jobs.Job')),
            ],
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.JobHandler'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.JobCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='jobhandler',
            unique_together=set([('character', 'job')]),
        ),
    ]
