# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('storyteller', '0002_auto_20160407_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, default=0.0)),
                ('reason', models.CharField(max_length=200)),
                ('date_awarded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='storyteller.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ExpLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_kinds', to='storyteller.CharacterTemplate')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_links', to='storyteller.ExpKind')),
            ],
        ),
        migrations.AddField(
            model_name='exp',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='storyteller.ExpLink'),
        ),
        migrations.AddField(
            model_name='exp',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.ObjectStub'),
        ),
        migrations.AlterUniqueTogether(
            name='explink',
            unique_together=set([('kind', 'character')]),
        ),
        migrations.AlterUniqueTogether(
            name='expkind',
            unique_together=set([('game', 'key')]),
        ),
    ]
