# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller', '0003_auto_20160408_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TemplateInfo',
            new_name='InfoKind',
        ),
        migrations.RemoveField(
            model_name='characterinfo',
            name='value',
        ),
        migrations.AlterField(
            model_name='characterinfo',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='storyteller.Info'),
        ),
        migrations.AddField(
            model_name='info',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='storyteller.InfoKind'),
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together=set([('key', 'kind')]),
        ),
    ]
