# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('comms', '0007_msg_db_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('channel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequency', to='comms.ChannelDB')),
            ],
        ),
        migrations.CreateModel(
            name='RadioSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('codename', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('on', models.BooleanField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio', to='objects.ObjectDB')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='radio.RadioFrequency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='radioslot',
            unique_together=set([('key', 'character'), ('codename', 'frequency')]),
        ),
    ]
