from __future__ import unicode_literals
from django.db import models

# Create your models here.
class PlayerSetting(models.Model):
    player = models.OneToOneField('players.PlayerDB', related_name='settings')
    look_alert = models.BooleanField(default=True)
    bbscan_alert = models.BooleanField(default=True)
    mail_alert = models.BooleanField(default=True)
    scenes_alert = models.BooleanField(default=True)
    namelink_channel = models.BooleanField(default=True)
    quotes_channel = models.CharField(max_length=25, default='n')
    speech_channel = models.CharField(max_length=25, default='n')
    border_color = models.CharField(max_length=25, default='M')
    columnname_color = models.CharField(max_length=25, default='G')
    headerstar_color = models.CharField(max_length=25, default='m')
    headertext_color = models.CharField(max_length=25, default='w')
    msgborder_color = models.CharField(max_length=25, default='m')
    msgtext_color = models.CharField(max_length=25, default='w')
    oocborder_color = models.CharField(max_length=25, default='x')
    ooctext_color = models.CharField(max_length=25, default='r')
    page_color = models.CharField(max_length=25, default='n')
    outpage_color = models.CharField(max_length=25, default='n')
    exitname_color = models.CharField(max_length=25, default='n')
    exitalias_color = models.CharField(max_length=25, default='n')


class GameSetting(models.Model):
    key = models.PositiveSmallIntegerField(default=1, unique=True, db_index=True)
    gbs_enabled = models.BooleanField(default=True)
    guest_post = models.BooleanField(default=True)
    approve_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    admin_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    default_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    guest_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    roleplay_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    alerts_channels = models.ManyToManyField('channels.ChannelDB', related_name='+')
    staff_tag = models.CharField(max_length=25, default='r')
    fclist_enable = models.BooleanField(default=True)
    guest_home = models.ForeignKey('objects.ObjectDB', related_name='+', null=True, on_delete=models.SET_NULL)
    character_home = models.ForeignKey('objects.ObjectDB', related_name='+', null=True, on_delete=models.SET_NULL)
    pot_timeout = models.PositiveIntegerField(default=28800)
    group_ic = models.BooleanField(default=True)
    group_ooc = models.BooleanField(default=True)
    anon_notices = models.BooleanField(default=False)
    public_email = models.EmailField(null=True)
    require_approval = models.BooleanField(default=False)
    scene_board = models.ForeignKey('bbs.Board', related_name='+', null=True, on_delete=models.SET_NULL)
    job_default = models.ForeignKey('job.Category', related_name='+', null=True, on_delete=models.SET_NULL)
    open_players = models.BooleanField(default=True)
    open_characters = models.BooleanField(default=True)


class CharacterSetting(models.Model):
    character = models.OneToOneField('objects.ObjectDB', related_name='settings')
    home = models.ForeignKey('objects.ObjectDB', related_name='+', null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey('players.PlayerDB', related_name='character_settings', null=True,on_delete=models.SET_NULL)
    radio_nospoof = models.BooleanField(default=False)
    group_ic = models.BooleanField(default=True)
    group_ooc = models.BooleanField(default=True)
    group_focus = models.ForeignKey('groups.Group', related_name='+', null=True, on_delete=models.SET_NULL)