# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 18:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbs', '0001_initial'),
        ('objects', '0009_remove_objectdb_db_player'),
        ('comms', '0016_remove_channeldb_db_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore', models.BooleanField(db_index=True, default=False)),
                ('date_made', models.DateTimeField(db_index=True)),
                ('text', models.TextField(blank=True)),
                ('codename', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('pitch', models.TextField(blank=True, default=None, null=True)),
                ('outcome', models.TextField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_scheduled', models.DateTimeField(null=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('public', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('log_ooc', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('log_channels', models.ManyToManyField(related_name='log_events', to='comms.ChannelDB')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('characters', models.ManyToManyField(related_name='event_pairings', to='objects.ObjectDB')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='scene.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('tag', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene', to='objects.ObjectDB')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scene.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_poses_here', to='objects.ObjectDB')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_poses', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='objects.ObjectDB')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='scene.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('mode', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='comms.ChannelDB')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poses_here', to='objects.ObjectDB')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene', to='scene.Plot'),
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='bbs.Post'),
        ),
        migrations.AddField(
            model_name='action',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scene.Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scene.Participant'),
        ),
        migrations.AddField(
            model_name='action',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scene.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('key', 'channel', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together=set([('plot', 'character')]),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('character', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together=set([('event', 'number')]),
        ),
    ]
