# Generated by Django 2.2.6 on 2019-11-23 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('building', '0002_auto_20191123_0343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MushAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MushAttributeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MushObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbref', models.CharField(db_index=True, max_length=15)),
                ('objid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('type', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('created', models.DateTimeField()),
                ('flags', models.TextField(blank=True)),
                ('powers', models.TextField(blank=True)),
                ('recreated', models.BooleanField(default=False)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to=settings.AUTH_USER_MODEL)),
                ('area', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to='building.AreaDB')),
                ('board', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to='forum.ForumBoardDB')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits_to', to='mush_import.MushObject')),
            ],
        ),
    ]
