# Generated by Django 2.2.6 on 2019-11-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factions', '0001_initial'),
        ('themes', '0001_initial'),
        ('mush_import', '0001_initial'),
        ('characters', '0012_merge_20191110_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushobject',
            name='fclist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to='themes.ThemeDB'),
        ),
        migrations.AddField(
            model_name='mushobject',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to='factions.FactionDB'),
        ),
        migrations.AddField(
            model_name='mushobject',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='mush_import.MushObject'),
        ),
        migrations.AddField(
            model_name='mushobject',
            name='obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mush', to='characters.ObjectDB'),
        ),
        migrations.AddField(
            model_name='mushobject',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned', to='mush_import.MushObject'),
        ),
        migrations.AddField(
            model_name='mushobject',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mush_import.MushObject'),
        ),
        migrations.AddField(
            model_name='mushattribute',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='mush_import.MushAttributeName'),
        ),
        migrations.AddField(
            model_name='mushattribute',
            name='dbref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='mush_import.MushObject'),
        ),
        migrations.AlterUniqueTogether(
            name='mushattribute',
            unique_together={('dbref', 'attr')},
        ),
    ]
