# Generated by Django 2.2.6 on 2019-11-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('core', '0001_initial'),
        ('characters', '0012_merge_20191110_2125'),
        ('typeclasses', '0013_auto_20191015_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadb',
            name='db_exit_typeclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exits', to='core.TypeclassMap'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_fixtures',
            field=models.ManyToManyField(related_name='areas', to='characters.ObjectDB'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory', to='core.EntityMapDB'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='building.AreaDB'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_room_typeclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building', to='core.TypeclassMap'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_tags',
            field=models.ManyToManyField(help_text='tags on this object. Tags are simple string markers to identify, group and alias characters.', to='typeclasses.Tag'),
        ),
        migrations.AddField(
            model_name='areadb',
            name='db_transient',
            field=models.ManyToManyField(related_name='current_areas', to='characters.ObjectDB'),
        ),
        migrations.AlterUniqueTogether(
            name='mappointdb',
            unique_together={('db_map', 'db_x_coordinate', 'db_y_coordinate', 'db_z_coordinate')},
        ),
        migrations.AlterUniqueTogether(
            name='gatewaydb',
            unique_together={('db_area', 'db_key')},
        ),
        migrations.AlterUniqueTogether(
            name='areadb',
            unique_together={('db_parent', 'db_key')},
        ),
    ]
