LOAD_ORDER = 0

INSTALLED_APPS = ()

LOCK_FUNC_MODULES = ()

INPUT_FUNC_MODULES = []

INLINE_FUNC_MODULES = []

CONFIGS = ()

ACCOUNT_HANDLERS = ()
CHARACTER_HANDLERS = ()
SCRIPT_HANDLERS = ()

ACCOUNT_STYLES = ()
CHARACTER_STYLES = ()
SCRIPT_STYLES = ()

VALIDATORS = ()

CMDSETS_ACCOUNT = ()

CMDSETS_CHARACTER = ('athanor_who.cmdsets.character.WhoCharacterCmdSet', )

CMDSETS_UNLOGGED = ()
