# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushobject',
            name='dbref',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='mushobject',
            name='objid',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='mushobject',
            name='type',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
