# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2016, 3, 14, 7, 40, 14, 435575, tzinfo=utc))),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2016, 3, 14, 7, 40, 14, 435594, tzinfo=utc))),
                ('text', models.TextField()),
                ('date_approved', models.DateTimeField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.ObjectStub')),
            ],
        ),
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, default='INFO', max_length=30)),
                ('character_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotypes', to='objects.ObjectDB')),
            ],
        ),
        migrations.AddField(
            model_name='infofile',
            name='info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='info.InfoType'),
        ),
        migrations.AddField(
            model_name='infofile',
            name='set_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.ObjectStub'),
        ),
    ]
