# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20160406_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 22, 25, 10, 935703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 22, 25, 10, 935722, tzinfo=utc)),
        ),
    ]
