# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20160407_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 16, 45, 42, 154404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 16, 45, 42, 154423, tzinfo=utc)),
        ),
    ]
