# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 06:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20160408_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 6, 8, 2, 693692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 6, 8, 2, 693711, tzinfo=utc)),
        ),
    ]
