# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, default=0.0)),
                ('reason', models.CharField(max_length=200)),
                ('date_awarded', models.DateTimeField(default=datetime.datetime(2016, 3, 14, 7, 40, 14, 437195, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ExpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, max_length=50)),
                ('character_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='objects.ObjectDB')),
            ],
        ),
    ]
