# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0001_initial'),
        ('groups', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exptype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='exp',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.ObjectStub'),
        ),
        migrations.AddField(
            model_name='exp',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='experience.ExpType'),
        ),
    ]
