# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('comms', '0007_msg_db_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ManyToManyField(related_name='gagging', to='comms.ChannelDB')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_gags', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('site', models.CharField(max_length=300)),
                ('result', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emit', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('codename', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms.ChannelDB')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Muzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DurationField()),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to='comms.ChannelDB')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to='objects.ObjectDB')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to=settings.AUTH_USER_MODEL)),
                ('setby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('duty', models.BooleanField(default=False)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_entry', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='WatchFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(related_name='on_watch', to='objects.ObjectDB')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='muzzle',
            unique_together=set([('channel', 'character'), ('channel', 'player')]),
        ),
    ]
