# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('comms', '0007_msg_db_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ManyToManyField(related_name='gagging', to='comms.ChannelDB')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_gags', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emit', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('codename', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms.ChannelDB')),
            ],
        ),
        migrations.CreateModel(
            name='Muzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('expires', models.DateTimeField()),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to='comms.ChannelDB')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to='objects.ObjectDB')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(null=True)),
                ('object', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stub', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(related_name='on_watch', to='objects.ObjectDB')),
            ],
        ),
        migrations.AddField(
            model_name='muzzle',
            name='setby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.ObjectStub'),
        ),
        migrations.AddField(
            model_name='message',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.ObjectStub'),
        ),
        migrations.AddField(
            model_name='message',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.PlayerStub'),
        ),
    ]
