# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        ('bbs', '0002_auto_20180217_0357'),
        ('comms', '0016_remove_channeldb_db_subscriptions'),
        ('groups', '0001_initial'),
        ('fclist', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcolor',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='admin_channels',
            field=models.ManyToManyField(related_name='_gamesetting_admin_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='alerts_channels',
            field=models.ManyToManyField(related_name='_gamesetting_alerts_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='approve_channels',
            field=models.ManyToManyField(related_name='_gamesetting_approve_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='character_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='default_channels',
            field=models.ManyToManyField(related_name='_gamesetting_default_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='event_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bbs.Board'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='fclist_status',
            field=models.ManyToManyField(related_name='_gamesetting_fclist_status_+', to='fclist.CharacterStatus'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='fclist_types',
            field=models.ManyToManyField(related_name='_gamesetting_fclist_types_+', to='fclist.CharacterType'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='guest_channels',
            field=models.ManyToManyField(related_name='_gamesetting_guest_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='guest_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.ObjectDB'),
        ),
    ]
