# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0016_remove_channeldb_db_subscriptions'),
        ('objects', '0009_remove_objectdb_db_player'),
        ('core', '0002_auto_20180217_0357'),
        ('jobs', '0001_initial'),
        ('groups', '0001_initial'),
        ('fclist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='job_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.JobCategory'),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='roleplay_channels',
            field=models.ManyToManyField(related_name='_gamesetting_roleplay_channels_+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='channel_gags',
            field=models.ManyToManyField(related_name='character_gags', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='channel_muzzles',
            field=models.ManyToManyField(related_name='character_muzzles', to='core.Muzzle'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_settings', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='fclist.CharacterStatus'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='character_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='fclist.CharacterType'),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='group_focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='charactercolor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_colors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactercolor',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='channelsetting',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='channelsetting',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='channelcolor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_colors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelcolor',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comms.ChannelDB'),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='channel_muzzles',
            field=models.ManyToManyField(related_name='account_muzzles', to='core.Muzzle'),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='friends',
            field=models.ManyToManyField(related_name='on_watch', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupcolor',
            unique_together=set([('owner', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='charactercolor',
            unique_together=set([('owner', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='channelcolor',
            unique_together=set([('owner', 'target')]),
        ),
    ]
