# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_auto_20160406_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 15, 6, 34, 763885, tzinfo=utc)),
        ),
    ]
