# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0006_auto_20160406_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 23, 45, 37, 375506, tzinfo=utc)),
        ),
    ]
