# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0017_auto_20160407_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 19, 44, 26, 526372, tzinfo=utc)),
        ),
    ]
