# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0019_auto_20160407_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 4, 3, 34, 759595, tzinfo=utc)),
        ),
    ]
