# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('order', models.IntegerField()),
                ('main', models.BooleanField(default=True)),
                ('lock_storage', models.TextField(blank=True, verbose_name=b'locks')),
                ('anonymous', models.CharField(max_length=80, null=True)),
                ('timeout', models.IntegerField(default=0, null=True)),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('post_text', models.TextField()),
                ('post_subject', models.CharField(max_length=30)),
                ('timeout', models.FloatField(null=True)),
                ('remaining_timeout', models.FloatField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bbs.Board')),
            ],
        ),
    ]
