# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('bbs', '0002_auto_20160314_0740'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='ignore_list',
            field=models.ManyToManyField(to='objects.ObjectDB'),
        ),
    ]
