# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0016_remove_channeldb_db_subscriptions'),
        ('objects', '0009_remove_objectdb_db_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChannelAccountMuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muzzles', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_muzzles', to='comms.ChannelDB')),
            ],
        ),
        migrations.CreateModel(
            name='PublicChannelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comms.ChannelDB')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_storage', models.TextField(blank=True, verbose_name=b'locks')),
                ('key', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='objects.ObjectDB')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='athanor.Zone')),
                ('rooms', models.ManyToManyField(related_name='zones', to='objects.ObjectDB')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([('owner', 'parent', 'key')]),
        ),
        migrations.AddIndex(
            model_name='publicchannelmessage',
            index=models.Index(fields=[b'channel', b'date_created'], name='athanor_pub_channel_7c9e64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicchannelaccountmuzzle',
            unique_together=set([('channel', 'account')]),
        ),
    ]
