# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 05:23


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athanor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcore',
            name='playtime',
            field=models.DurationField(verbose_name=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='charactercore',
            name='playtime',
            field=models.DurationField(verbose_name=datetime.timedelta(0)),
        ),
    ]
