# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athanor', '0003_auto_20180425_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterwho',
            name='account',
        ),
        migrations.DeleteModel(
            name='CharacterWho',
        ),
    ]
