# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        ('athanor', '0004_auto_20180425_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterWho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('dark', models.BooleanField(default=False)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
            ],
        ),
    ]
