# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athanor', '0005_characterwho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountwho',
            name=b'account',
        ),
        migrations.RemoveField(
            model_name='characterwho',
            name=b'character',
        ),
        migrations.DeleteModel(
            name='AccountWho',
        ),
        migrations.DeleteModel(
            name='CharacterWho',
        ),
    ]
