# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athanor', '0006_auto_20180427_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
            ],
        ),
    ]
