# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0007_auto_20150403_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('game_type', models.CharField(max_length=80)),
                ('game_site', models.CharField(blank=True, max_length=200, null=True)),
                ('game_port', models.IntegerField(default=0)),
                ('bot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bot_pass', models.CharField(blank=True, max_length=200, null=True)),
                ('mssp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mssp_players', models.IntegerField(default=0)),
                ('mssp_uptime', models.IntegerField(default=0)),
                ('mssp_pueblo', models.BooleanField(default=0)),
                ('mssp_codebase', models.CharField(blank=True, max_length=200, null=True)),
                ('mssp_family', models.CharField(blank=True, max_length=200, null=True)),
                ('mssp_website', models.CharField(blank=True, max_length=200, null=True)),
                ('mssp_ansi', models.BooleanField(default=0)),
                ('mssp_x256', models.BooleanField(default=0)),
                ('bot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database', to='scripts.ScriptDB')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together=set([('bot_name', 'game_site')]),
        ),
    ]
