# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botnet', '0002_auto_20160425_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSSPField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_ansi',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_codebase',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_family',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_name',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_players',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_pueblo',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_uptime',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_website',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='mssp_x256',
        ),
        migrations.AddField(
            model_name='msspfield',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mssp', to='botnet.Bot'),
        ),
        migrations.AlterUniqueTogether(
            name='msspfield',
            unique_together=set([('game', 'field')]),
        ),
    ]
