# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botnet', '0003_auto_20160426_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='game_server',
            field=models.CharField(default='PennMUSH', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='game_type',
            field=models.CharField(max_length=200),
        ),
    ]
